import { Option } from './types';

export const PROVINCES: Option[] = [
  { value: '01', label: 'Adana' },
  { value: '02', label: 'Adıyaman' },
  { value: '03', label: 'Afyonkarahisar' },
  { value: '04', label: 'Ağrı' },
  { value: '05', label: 'Amasya' },
  { value: '06', label: 'Ankara' },
  { value: '07', label: 'Antalya' },
  { value: '08', label: 'Artvin' },
  { value: '09', label: 'Aydın' },
  { value: '10', label: 'Balıkesir' },
  { value: '11', label: 'Bilecik' },
  { value: '12', label: 'Bingöl' },
  { value: '13', label: 'Bitlis' },
  { value: '14', label: 'Bolu' },
  { value: '15', label: 'Burdur' },
  { value: '16', label: 'Bursa' },
  { value: '17', label: 'Çanakkale' },
  { value: '18', label: 'Çankırı' },
  { value: '19', label: 'Çorum' },
  { value: '20', label: 'Denizli' },
  { value: '21', label: 'Diyarbakır' },
  { value: '22', label: 'Edirne' },
  { value: '23', label: 'Elazığ' },
  { value: '24', label: 'Erzincan' },
  { value: '25', label: 'Erzurum' },
  { value: '26', label: 'Eskişehir' },
  { value: '27', label: 'Gaziantep' },
  { value: '28', label: 'Giresun' },
  { value: '29', label: 'Gümüşhane' },
  { value: '30', label: 'Hakkâri' },
  { value: '31', label: 'Hatay' },
  { value: '32', label: 'Isparta' },
  { value: '33', label: 'Mersin' },
  { value: '34', label: 'İstanbul' },
  { value: '35', label: 'İzmir' },
  { value: '36', label: 'Kars' },
  { value: '37', label: 'Kastamonu' },
  { value: '38', label: 'Kayseri' },
  { value: '39', label: 'Kırklareli' },
  { value: '40', label: 'Kırşehir' },
  { value: '41', label: 'Kocaeli' },
  { value: '42', label: 'Konya' },
  { value: '43', label: 'Kütahya' },
  { value: '44', label: 'Malatya' },
  { value: '45', label: 'Manisa' },
  { value: '46', label: 'Kahramanmaraş' },
  { value: '47', label: 'Mardin' },
  { value: '48', label: 'Muğla' },
  { value: '49', label: 'Muş' },
  { value: '50', label: 'Nevşehir' },
  { value: '51', label: 'Niğde' },
  { value: '52', label: 'Ordu' },
  { value: '53', label: 'Rize' },
  { value: '54', label: 'Sakarya' },
  { value: '55', label: 'Samsun' },
  { value: '56', label: 'Siirt' },
  { value: '57', label: 'Sinop' },
  { value: '58', label: 'Sivas' },
  { value: '59', label: 'Tekirdağ' },
  { value: '60', label: 'Tokat' },
  { value: '61', label: 'Trabzon' },
  { value: '62', label: 'Tunceli' },
  { value: '63', label: 'Şanlıurfa' },
  { value: '64', label: 'Uşak' },
  { value: '65', label: 'Van' },
  { value: '66', label: 'Yozgat' },
  { value: '67', label: 'Zonguldak' },
  { value: '68', label: 'Aksaray' },
  { value: '69', label: 'Bayburt' },
  { value: '70', label: 'Karaman' },
  { value: '71', label: 'Kırıkkale' },
  { value: '72', label: 'Batman' },
  { value: '73', label: 'Şırnak' },
  { value: '74', label: 'Bartın' },
  { value: '75', label: 'Ardahan' },
  { value: '76', label: 'Iğdır' },
  { value: '77', label: 'Yalova' },
  { value: '78', label: 'Karabük' },
  { value: '79', label: 'Kilis' },
  { value: '80', label: 'Osmaniye' },
  { value: '81', label: 'Düzce' }
];

export const DISTRICTS: Record<string, Option[]> = {
  '01': [
    { value: 'ALADAĞ', label: 'Aladağ' }, { value: 'CEYHAN', label: 'Ceyhan' }, { value: 'ÇUKUROVA', label: 'Çukurova' }, { value: 'FEKE', label: 'Feke' }, { value: 'İMAMOĞLU', label: 'İmamoğlu' }, { value: 'KARAİSALI', label: 'Karaisalı' }, { value: 'KARATAŞ', label: 'Karataş' }, { value: 'KOZAN', label: 'Kozan' }, { value: 'POZANTI', label: 'Pozantı' }, { value: 'SAİMBEYLİ', label: 'Saimbeyli' }, { value: 'SARIÇAM', label: 'Sarıçam' }, { value: 'SEYHAN', label: 'Seyhan' }, { value: 'TUFANBEYLİ', label: 'Tufanbeyli' }, { value: 'YUMURTALIK', label: 'Yumurtalık' }, { value: 'YÜREĞİR', label: 'Yüreğir' }
  ],
  '06': [
    { value: 'AKYURT', label: 'Akyurt' }, { value: 'ALTINDAĞ', label: 'Altındağ' }, { value: 'AYAŞ', label: 'Ayaş' }, { value: 'BALA', label: 'Bala' }, { value: 'BEYPAZARI', label: 'Beypazarı' }, { value: 'ÇAMLIDERE', label: 'Çamlıdere' }, { value: 'ÇANKAYA', label: 'Çankaya' }, { value: 'ÇUBUK', label: 'Çubuk' }, { value: 'ELMADAĞ', label: 'Elmadağ' }, { value: 'ETİMESGUT', label: 'Etimesgut' }, { value: 'EVREN', label: 'Evren' }, { value: 'GÖLBAŞI', label: 'Gölbaşı' }, { value: 'GÜDÜL', label: 'Güdül' }, { value: 'HAYMANA', label: 'Haymana' }, { value: 'KAHRAMANKAZAN', label: 'Kahramankazan' }, { value: 'KALECİK', label: 'Kalecik' }, { value: 'KEÇİÖREN', label: 'Keçiören' }, { value: 'KIZILCAHAMAM', label: 'Kızılcahamam' }, { value: 'MAMAK', label: 'Mamak' }, { value: 'NALLIHAN', label: 'Nallıhan' }, { value: 'POLATLI', label: 'Polatlı' }, { value: 'PURSAKLAR', label: 'Pursaklar' }, { value: 'SİNCAN', label: 'Sincan' }, { value: 'ŞEREFLİKOÇHİSAR', label: 'Şereflikoçhisar' }, { value: 'YENİMAHALLE', label: 'Yenimahalle' }
  ],
  '07': [
    { value: 'AKSEKİ', label: 'Akseki' }, { value: 'AKSU', label: 'Aksu' }, { value: 'ALANYA', label: 'Alanya' }, { value: 'DEMRE', label: 'Demre' }, { value: 'DÖŞEMEALTI', label: 'Döşemealtı' }, { value: 'ELMALI', label: 'Elmalı' }, { value: 'FİNİKE', label: 'Finike' }, { value: 'GAZİPAŞA', label: 'Gazipaşa' }, { value: 'GÜNDOĞMUŞ', label: 'Gündoğmuş' }, { value: 'İBRADI', label: 'İbradı' }, { value: 'KAŞ', label: 'Kaş' }, { value: 'KEMER', label: 'Kemer' }, { value: 'KEPEZ', label: 'Kepez' }, { value: 'KONYAALTI', label: 'Konyaaltı' }, { value: 'KORKUTELİ', label: 'Korkuteli' }, { value: 'KUMLUCA', label: 'Kumluca' }, { value: 'MANAVGAT', label: 'Manavgat' }, { value: 'MURATPAŞA', label: 'Muratpaşa' }, { value: 'SERİK', label: 'Serik' }
  ],
  '16': [
    { value: 'BÜYÜKORHAN', label: 'Büyükorhan' }, { value: 'GEMLİK', label: 'Gemlik' }, { value: 'GÜRSU', label: 'Gürsu' }, { value: 'HARMANCIK', label: 'Harmancık' }, { value: 'İNEGÖL', label: 'İnegöl' }, { value: 'İZNİK', label: 'İznik' }, { value: 'KARACABEY', label: 'Karacabey' }, { value: 'KELES', label: 'Keles' }, { value: 'KESTEL', label: 'Kestel' }, { value: 'MUDANYA', label: 'Mudanya' }, { value: 'MUSTAFAKEMALPAŞA', label: 'Mustafakemalpaşa' }, { value: 'NİLÜFER', label: 'Nilüfer' }, { value: 'ORHANELİ', label: 'Orhaneli' }, { value: 'ORHANGAZİ', label: 'Orhangazi' }, { value: 'OSMANGAZİ', label: 'Osmangazi' }, { value: 'YENİŞEHİR', label: 'Yenişehir' }, { value: 'YILDIRIM', label: 'Yıldırım' }
  ],
  '34': [
    { value: 'ADALAR', label: 'Adalar' }, { value: 'ARNAVUTKÖY', label: 'Arnavutköy' }, { value: 'ATAŞEHİR', label: 'Ataşehir' }, { value: 'AVCILAR', label: 'Avcılar' }, { value: 'BAĞCILAR', label: 'Bağcılar' }, { value: 'BAHÇELİEVLER', label: 'Bahçelievler' }, { value: 'BAKIRKÖY', label: 'Bakırköy' }, { value: 'BAŞAKŞEHİR', label: 'Başakşehir' }, { value: 'BAYRAMPAŞA', label: 'Bayrampaşa' }, { value: 'BEŞİKTAŞ', label: 'Beşiktaş' }, { value: 'BEYKOZ', label: 'Beykoz' }, { value: 'BEYLİKDÜZÜ', label: 'Beylikdüzü' }, { value: 'BEYOĞLU', label: 'Beyoğlu' }, { value: 'BÜYÜKÇEKMECE', label: 'Büyükçekmece' }, { value: 'ÇATALCA', label: 'Çatalca' }, { value: 'ÇEKMEKÖY', label: 'Çekmeköy' }, { value: 'ESENLER', label: 'Esenler' }, { value: 'ESENYURT', label: 'Esenyurt' }, { value: 'EYÜPSULTAN', label: 'Eyüpsultan' }, { value: 'FATİH', label: 'Fatih' }, { value: 'GAZİOSMANPAŞA', label: 'Gaziosmanpaşa' }, { value: 'GÜNGÖREN', label: 'Güngören' }, { value: 'KADIKÖY', label: 'Kadıköy' }, { value: 'KAĞITHANE', label: 'Kağıthane' }, { value: 'KARTAL', label: 'Kartal' }, { value: 'KÜÇÜKÇEKMECE', label: 'Küçükçekmece' }, { value: 'MALTEPE', label: 'Maltepe' }, { value: 'PENDİK', label: 'Pendik' }, { value: 'SANCAKTEPE', label: 'Sancaktepe' }, { value: 'SARIYER', label: 'Sarıyer' }, { value: 'SİLİVRİ', label: 'Silivri' }, { value: 'SULTANBEYLİ', label: 'Sultanbeyli' }, { value: 'SULTANGAZİ', label: 'Sultangazi' }, { value: 'ŞİLE', label: 'Şile' }, { value: 'ŞİŞLİ', label: 'Şişli' }, { value: 'TUZLA', label: 'Tuzla' }, { value: 'ÜMRANİYE', label: 'Ümraniye' }, { value: 'ÜSKÜDAR', label: 'Üsküdar' }, { value: 'ZEYTİNBURNU', label: 'Zeytinburnu' }
  ],
  '35': [
    { value: 'ALİAĞA', label: 'Aliağa' }, { value: 'BALÇOVA', label: 'Balçova' }, { value: 'BAYINDIR', label: 'Bayındır' }, { value: 'BAYRAKLI', label: 'Bayraklı' }, { value: 'BERGAMA', label: 'Bergama' }, { value: 'BEYDAĞ', label: 'Beydağ' }, { value: 'BORNOVA', label: 'Bornova' }, { value: 'BUCA', label: 'Buca' }, { value: 'ÇEŞME', label: 'Çeşme' }, { value: 'ÇİĞLİ', label: 'Çiğli' }, { value: 'DİKİLİ', label: 'Dikili' }, { value: 'FOÇA', label: 'Foça' }, { value: 'GAZİEMİR', label: 'Gaziemir' }, { value: 'GÜZELBAHÇE', label: 'Güzelbahçe' }, { value: 'KARABAĞLAR', label: 'Karabağlar' }, { value: 'KARABURUN', label: 'Karaburun' }, { value: 'KARŞIYAKA', label: 'Karşıyaka' }, { value: 'KEMALPAŞA', label: 'Kemalpaşa' }, { value: 'KINIK', label: 'Kınık' }, { value: 'KİRAZ', label: 'Kiraz' }, { value: 'KONAK', label: 'Konak' }, { value: 'MENDERES', label: 'Menderes' }, { value: 'MENEMEN', label: 'Menemen' }, { value: 'NARLIDERE', label: 'Narlıdere' }, { value: 'ÖDEMİŞ', label: 'Ödemiş' }, { value: 'SEFERİHİSAR', label: 'Seferihisar' }, { value: 'SELÇUK', label: 'Selçuk' }, { value: 'TİRE', label: 'Tire' }, { value: 'TORBALI', label: 'Torbalı' }, { value: 'URLA', label: 'Urla' }
  ],
};

export const NEIGHBORHOODS: Record<string, Record<string, Option[]>> = {
    '16': { // Bursa
        'YILDIRIM': [
            { value: '152EVLER MAHALLESİ', label: '152 Evler' },
            { value: '75. YIL MAHALLESİ', label: '75. Yıl' },
            { value: 'AKÇAĞLAYAN MAHALLESİ', label: 'Akçağlayan' },
            { value: 'ANADOLU MAHALLESİ', label: 'Anadolu' },
            { value: 'ARABAYATAĞI MAHALLESİ', label: 'Arabayatağı' },
            { value: 'BAĞLARALTI MAHALLESİ', label: 'Bağlaraltı' },
            { value: 'BARUTHANE MAHALLESİ', label: 'Baruthane' },
            { value: 'BEYAZIT MAHALLESİ', label: 'Beyazıt' },
            { value: 'ÇINARÖNÜ MAHALLESİ', label: 'Çınarönü' },
            { value: 'CUMALIKIZIK MAHALLESİ', label: 'Cumalıkızık' },
            { value: 'DAVUTDEDE MAHALLESİ', label: 'Davutdede' },
            { value: 'DAVUTKADI MAHALLESİ', label: 'Davutkadı' },
            { value: 'DEĞİRMENLİKIZIK MAHALLESİ', label: 'Değirmenlikızık' },
            { value: 'DEMETEVLER MAHALLESİ', label: 'Demetevler' },
            { value: 'DUAÇINARI MAHALLESİ', label: 'Duaçınarı' },
            { value: 'EĞİTİM MAHALLESİ', label: 'Eğitim' },
            { value: 'EMİRSULTAN MAHALLESİ', label: 'Emirsultan' },
            { value: 'ERİKLİ MAHALLESİ', label: 'Erikli' },
            { value: 'ERTUĞRULGAZİ MAHALLESİ', label: 'Ertuğrulgazi' },
            { value: 'ESENEVLER MAHALLESİ', label: 'Esenevler' },
            { value: 'FATİH SULTAN MEHMET MAHALLESİ', label: 'Fatih Sultan Mehmet' },
            { value: 'FİDYEKIZIK MAHALLESİ', label: 'Fidyekızık' },
            { value: 'GÜLLÜK MAHALLESİ', label: 'Güllük' },
            { value: 'HACİSEYFETTİN MAHALLESİ', label: 'Hacıseyfettin' },
            { value: 'HACIVAT MAHALLESİ', label: 'Hacivat' },
            { value: 'HAMAMLIKIZIK MAHALLESİ', label: 'Hamamlıkızık' },
            { value: 'HOCATAŞKIN MAHALLESİ', label: 'Hocataşkın' },
            { value: 'İSABEY MAHALLESİ', label: 'İsabey' },
            { value: 'KAPLIKAYA MAHALLESİ', label: 'Kaplıkaya' },
            { value: 'KARAAĞAÇ MAHALLESİ', label: 'Karaağaç' },
            { value: 'KARAMAZAK MAHALLESİ', label: 'Karamazak' },
            { value: 'KARAPINAR MAHALLESİ', label: 'Karapınar' },
            { value: 'KAZIM KARABEKİR MAHALLESİ', label: 'Kazım Karabekir' },
            { value: 'KURTOĞLU MAHALLESİ', label: 'Kurtoğlu' },
            { value: 'MALTEPE MAHALLESİ', label: 'Maltepe' },
            { value: 'MEHMETAKİFERSOY MAHALLESİ', label: 'Mehmetakifersoy' },
            { value: 'MEVLANA MAHALLESİ', label: 'Mevlana' },
            { value: 'MEYDANCIK MAHALLESİ', label: 'Meydancık' },
            { value: 'MİMARSİNAN MAHALLESİ', label: 'Mimarsinan' },
            { value: 'MİLLET MAHALLESİ', label: 'Millet' },
            { value: 'MOLLAARAP MAHALLESİ', label: 'Mollaarap' },
            { value: 'MUSABABA MAHALLESİ', label: 'Musababa' },
            { value: 'NAMAZGAH MAHALLESİ', label: 'Namazgah' },
            { value: 'ORHANGAZİ MAHALLESİ', label: 'Orhangazi' },
            { value: 'ORTABAĞLAR MAHALLESİ', label: 'Ortabağlar' },
            { value: 'PİREMİR MAHALLESİ', label: 'Piremir' },
            { value: 'SAMANLI MAHALLESİ', label: 'Samanlı' },
            { value: 'SELÇUKBEY MAHALLESİ', label: 'Selçukbey' },
            { value: 'SELİMZADE MAHALLESİ', label: 'Selimzade' },
            { value: 'SIRACEVİZLER MAHALLESİ', label: 'Sıracevizler' },
            { value: 'SİNANDEDE MAHALLESİ', label: 'Sinandede' },
            { value: 'ŞİRİNEVLER MAHALLESİ', label: 'Şirinevler' },
            { value: 'ŞÜKRANİYE MAHALLESİ', label: 'Şükraniye' },
            { value: 'TEFERRÜÇ MAHALLESİ', label: 'Teferrüç' },
            { value: 'ULUS MAHALLESİ', label: 'Ulus' },
            { value: 'UMURBEY MAHALLESİ', label: 'Umurbey' },
            { value: 'VAKIF MAHALLESİ', label: 'Vakıf' },
            { value: 'VATAN MAHALLESİ', label: 'Vatan' },
            { value: 'YAVUZSELIM MAHALLESİ', label: 'Yavuzselim' },
            { value: 'YEDİSELVİLER MAHALLESİ', label: 'Yediselviler' },
            { value: 'YENİ MAHALLE MAHALLESİ', label: 'Yeni Mahalle' },
            { value: 'YENİDOĞAN MAHALLESİ', label: 'Yenidoğan' },
            { value: 'YENİMAHALLE MAHALLESİ', label: 'Yenimahalle' },
            { value: 'YEŞİL MAHALLESİ', label: 'Yeşil' },
            { value: 'YEŞİLYAYLA MAHALLESİ', label: 'Yeşilyayla' },
            { value: 'YIĞITALI MAHALLESİ', label: 'Yiğitali' },
            { value: 'YILDIRIM MAHALLESİ', label: 'Yıldırım' },
            { value: 'ZÜMRÜTEVLER MAHALLESİ', label: 'Zümrütevler' },
        ],
        'OSMANGAZİ': [
            { value: 'ADALET MAHALLESİ', label: 'Adalet' },
            { value: 'AHMETPAŞA MAHALLESİ', label: 'Ahmetpaşa' },
            { value: 'AKPINAR MAHALLESİ', label: 'Akpınar' },
            { value: 'AKTİMESCİT MAHALLESİ', label: 'Aktimescit' },
            { value: 'ALAADDİN MAHALLESİ', label: 'Alaaddin' },
            { value: 'ALACAHIRKA MAHALLESİ', label: 'Alacahırka' },
            { value: 'ALEMDAR MAHALLESİ', label: 'Alemdar' },
            { value: 'ALİPAŞA MAHALLESİ', label: 'Alipaşa' },
            { value: 'ALTINOVA MAHALLESİ', label: 'Altınova' },
            { value: 'ALTIPARMAK MAHALLESİ', label: 'Altıparmak' },
            { value: 'AHMETBEY MAHALLESİ', label: 'Ahmetbey' },
            { value: 'ATAEVLER MAHALLESİ', label: 'Ataevler' },
            { value: 'BAĞLARBAŞI MAHALLESİ', label: 'Bağlarbaşı' },
            { value: 'BAHAR MAHALLESİ', label: 'Bahar' },
            { value: 'BAŞARAN MAHALLESİ', label: 'Başaran' },
            { value: 'ÇEKİRGE MAHALLESİ', label: 'Çekirge' },
            { value: 'ÇIRPAN MAHALLESİ', label: 'Çırpan' },
            { value: 'DEMİRKAPI MAHALLESİ', label: 'Demirkapı' },
            { value: 'DEMİRTAŞ MAHALLESİ', label: 'Demirtaş' },
            { value: 'DOBBUROLU MAHALLESİ', label: 'Dobruca' },
            { value: 'DOĞANBEY MAHALLESİ', label: 'Doğanbey' },
            { value: 'DİKKALDIRIM MAHALLESİ', label: 'Dikkaldırım' },
            { value: 'ELMASBAHÇELER MAHALLESİ', label: 'Elmasbahçeler' },
            { value: 'EMEK MAHALLESİ', label: 'Emek' },
            { value: 'FATİH MAHALLESİ', label: 'Fatih' },
            { value: 'GAZİAKDEMİR MAHALLESİ', label: 'Gaziakdemir' },
            { value: 'GEÇİT MAHALLESİ', label: 'Geçit' },
            { value: 'GÜLBAHÇE MAHALLESİ', label: 'Gülbahçe' },
            { value: 'GÜNEŞTEPE MAHALLESİ', label: 'Güneştepe' },
            { value: 'HAMİTLER MAHALLESİ', label: 'Hamitler' },
            { value: 'HAMZABEY MAHALLESİ', label: 'Hamzabey' },
            { value: 'HOCAALİZADE MAHALLESİ', label: 'Hocaalizade' },
            { value: 'HÜDAVENDİGAR MAHALLESİ', label: 'Hüdavendigar' },
            { value: 'HÜRRİYET MAHALLESİ', label: 'Hürriyet' },
            { value: 'İBRAHİMPAŞA MAHALLESİ', label: 'İbrahimpaşa' },
            { value: 'İNKAYA MAHALLESİ', label: 'İnkaya' },
            { value: 'İNTİZAM MAHALLESİ', label: 'İntizam' },
            { value: 'İSTİKLAL MAHALLESİ', label: 'İstiklal' },
            { value: 'KEMERÇEŞME MAHALLESİ', label: 'Kemerçeşme' },
            { value: 'KOCANAİP MAHALLESİ', label: 'Kocanaip' },
            { value: 'KOĞUKÇINAR MAHALLESİ', label: 'Koğukçınar' },
            { value: 'KÜKÜRTLÜ MAHALLESİ', label: 'Kükürtlü' },
            { value: 'KÜPLÜPINAR MAHALLESİ', label: 'Küplüpınar' },
            { value: 'MAKSEM MAHALLESİ', label: 'Maksem' },
            { value: 'MEHMETAKİF MAHALLESİ', label: 'Mehmetakif' },
            { value: 'MOL എന്ന് MAHALLESİ', label: 'Mollafenari' },
            { value: 'MOLLAGÜRANİ MAHALLESİ', label: 'Mollagürani' },
            { value: 'MURADİYE MAHALLESİ', label: 'Muradiye' },
            { value: 'MUTLUEVLER MAHALLESİ', label: 'Mutluevler' },
            { value: 'NAMIKKEMAL MAHALLESİ', label: 'Namıkkemal' },
            { value: 'Nalbantoğlu MAHALLESİ', label: 'Nalbantoğlu' },
            { value: 'ORHANBEY MAHALLESİ', label: 'Orhanbey' },
            { value: 'OSMANGAZİ MAHALLESİ', label: 'Osmangazi' },
            { value: 'OVAAKÇA MAHALLESİ', label: 'Ovaakça' },
            { value: 'PANAYIR MAHALLESİ', label: 'Panayır' },
            { value: 'PINARBAŞI MAHALLESİ', label: 'Pınarbaşı' },
            { value: 'REŞİTPAŞA MAHALLESİ', label: 'Reşitpaşa' },
            { value: 'SAKARYA MAHALLESİ', label: 'Sakarya' },
            { value: 'SANTRALGARAGE MAHALLESİ', label: 'Santralgarage' },
            { value: 'SELAMET MAHALLESİ', label: 'Selamet' },
            { value: 'SELÇUKGAZİ MAHALLESİ', label: 'Selçukgazi' },
            { value: 'SELEhattin GAZİ MAHALLESİ', label: 'Selahattin Gazi' },
            { value: 'SIRAMEŞELER MAHALLESİ', label: 'Sırameşeler' },
            { value: 'SOĞANLI MAHALLESİ', label: 'Soğanlı' },
            { value: 'ŞEHABETTİNPAŞA MAHALLESİ', label: 'Şahabettinpaşa' },
            { value: 'ŞEHREKÜSTÜ MAHALLESİ', label: 'Şehreküstü' },
            { value: 'TAHTAKALE MAHALLESİ', label: 'Tahtakale' },
            { value: 'TAYAKADIN MAHALLESİ', label: 'Tayakadın' },
            { value: 'TUNA MAHALLESİ', label: 'Tuna' },
            { value: 'ULU MAHALLESİ', label: 'Ulu' },
            { value: 'ULUÇAM MAHALLESİ', label: 'Uluçam' },
            { value: 'YAHŞİBEY MAHALLESİ', label: 'Yahşibey' },
            { value: 'YENİBAĞLAR MAHALLESİ', label: 'Yenibağlar' },
            { value: 'YENİCEABAT MAHALLESİ', label: 'Yeniceabat' },
            { value: 'YENİKARAMAN MAHALLESİ', label: 'Yenikaraman' },
            { value: 'YENİKENT MAHALLESİ', label: 'Yenikent' },
            { value: 'YEŞİLOVA MAHALLESİ', label: 'Yeşilova' },
            { value: 'YUNUSELİ MAHALLESİ', label: 'Yunuseli' },
            { value: 'ZAFER MAHALLESİ', label: 'Zafer' },
        ],
        'NİLÜFER': [
            { value: '19 MAYIS MAHALLESİ', label: '19 Mayıs' },
            { value: '23 NİSAN MAHALLESİ', label: '23 Nisan' },
            { value: '30 AĞUSTOS ZAFER MAHALLESİ', label: '30 Ağustos Zafer' },
            { value: 'AHMET YESEVİ MAHALLESİ', label: 'Ahmet Yesevi' },
            { value: 'AKÇALAR MAHALLESİ', label: 'Akçalar' },
            { value: 'ALAADDİNBEY MAHALLESİ', label: 'Alaaddinbey' },
            { value: 'ALTINŞEHİR MAHALLESİ', label: 'Altınşehir' },
            { value: 'ATAEVLER MAHALLESİ', label: 'Ataevler' },
            { value: 'ATLAS MAHALLESİ', label: 'Atlas' },
            { value: 'AYVAKÖY MAHALLESİ', label: 'Ayvaköy' },
            { value: 'BADIRGA MAHALLESİ', label: 'Badırga' },
            { value: 'BALAT MAHALLESİ', label: 'Balat' },
            { value: 'BALKAN MAHALLESİ', label: 'Balkan' },
            { value: 'BARIŞ MAHALLESİ', label: 'Barış' },
            { value: 'BAŞKÖY MAHALLESİ', label: 'Başköy' },
            { value: 'BEŞEVLER MAHALLESİ', label: 'Beşevler' },
            { value: 'BÜYÜKBALIKLI MAHALLESİ', label: 'Büyükbalıklı' },
            { value: 'CUMHURİYET MAHALLESİ', label: 'Cumhuriyet' },
            { value: 'ÇALI MAHALLESİ', label: 'Çalı' },
            { value: 'ÇAMLICA MAHALLESİ', label: 'Çamlıca' },
            { value: 'ÇAYLI MAHALLESİ', label: 'Çaylı' },
            { value: 'DAĞYENİCE MAHALLESİ', label: 'Dağyenice' },
            { value: 'DEMİRCİ MAHALLESİ', label: 'Demirci' },
            { value: 'DOĞANKÖY MAHALLESİ', label: 'Doğanköy' },
            { value: 'DUMLUPINAR MAHALLESİ', label: 'Dumlupınar' },
            { value: 'ERTUĞRUL MAHALLESİ', label: 'Ertuğrul' },
            { value: 'ESENTEPE MAHALLESİ', label: 'Esentepe' },
            { value: 'FADILLI MAHALLESİ', label: 'Fadıllı' },
            { value: 'FETHİYE MAHALLESİ', label: 'Fethiye' },
            { value: 'GÖKÇE MAHALLESİ', label: 'Gökçe' },
            { value: 'GÖLYAZI MAHALLESİ', label: 'Gölyazı' },
            { value: 'GÜMÜŞTEPE MAHALLESİ', label: 'Gümüştepe' },
            { value: 'GÜNGÖREN MAHALLESİ', label: 'Güngören' },
            { value: 'HASANAĞA MAHALLESİ', label: 'Hasanağa' },
            { value: 'IŞIKTEPE MAHALLESİ', label: 'Işıktepe' },
            { value: 'İHSANİYE MAHALLESİ', label: 'İhsaniye' },
            { value: 'İNEGAZİ MAHALLESİ', label: 'İnegazi' },
            { value: 'İRFANİYE MAHALLESİ', label: 'İrfaniye' },
            { value: 'KADRİYE MAHALLESİ', label: 'Kadriye' },
            { value: 'KARACAOBA MAHALLESİ', label: 'Karacaoba' },
            { value: 'KARAMAN MAHALLESİ', label: 'Karaman' },
            { value: 'KAYAPA MAHALLESİ', label: 'Kayapa' },
            { value: 'KIZILCIKLI MAHALLESİ', label: 'Kızılcıklı' },
            { value: 'KONAK MAHALLESİ', label: 'Konak' },
            { value: 'KONAKLI MAHALLESİ', label: 'Konaklı' },
            { value: 'KURTULUŞ MAHALLESİ', label: 'Kurtuluş' },
            { value: 'KÜLTÜR MAHALLESİ', label: 'Kültür' },
            { value: 'MAKŞEMPINARI MAHALLESİ', label: 'Makşempınarı' },
            { value: 'MİNARELİÇAVUŞ MAHALLESİ', label: 'Minareliçavuş' },
            { value: 'ODUNLUK MAHALLESİ', label: 'Odunluk' },
            { value: 'ÖZLÜCE MAHALLESİ', label: 'Özlüce' },
            { value: 'TAHTALI MAHALLESİ', label: 'Tahtalı' },
            { value: 'UNÇUKURU MAHALLESİ', label: 'Unçukuru' },
            { value: 'ÜÇEVLER MAHALLESİ', label: 'Üçevler' },
            { value: 'ÜÇPINAR MAHALLESİ', label: 'Üçpınar' },
            { value: 'ÜMRANİYE MAHALLESİ', label: 'Ümraniye' },
            { value: 'YAYLACIK MAHALLESİ', label: 'Yaylacık' },
            { value: 'YOLÇATI MAHALLESİ', label: 'Yolçatı' },
            { value: 'YÜZÜNCÜYIL MAHALLESİ', label: 'Yüzüncüyıl' },
        ]
    }
};

export const MAIN_CATEGORIES: Option[] = [
    { value: 'Yeme & İçme', label: 'Yeme & İçme' },
    { value: 'Alışveriş', label: 'Alışveriş' },
    { value: 'Sağlık & Medikal', label: 'Sağlık & Medikal' },
    { value: 'Güzellik & Kişisel Bakım', label: 'Güzellik & Kişisel Bakım' },
    { value: 'Otomotiv', label: 'Otomotiv' },
    { value: 'Eğlence & Etkinlik', label: 'Eğlence & Etkinlik' },
    { value: 'Spor & Fitness', label: 'Spor & Fitness' },
    { value: 'Profesyonel Hizmetler', label: 'Profesyonel Hizmetler' },
    { value: 'Ev & Bahçe Hizmetleri', label: 'Ev & Bahçe Hizmetleri' },
    { value: 'Eğitim', label: 'Eğitim' },
    { value: 'Finans & Hukuk', label: 'Finans & Hukuk' },
    { value: 'Konaklama & Seyahat', label: 'Konaklama & Seyahat' },
    { value: 'Kamu & Dini Kuruluşlar', label: 'Kamu & Dini Kuruluşlar' },
];

export const SUB_CATEGORIES: Record<string, Option[]> = {
    'Yeme & İçme': [
        { value: 'Restoran', label: 'Restoran' },
        { value: 'Kafe', label: 'Kafe' },
        { value: 'Bar & Pub', label: 'Bar & Pub' },
        { value: 'Pastane & Fırın', label: 'Pastane & Fırın' },
        { value: 'Büfe & Sandviç Dükkanı', label: 'Büfe & Sandviç Dükkanı' },
        { value: 'Fast Food', label: 'Fast Food' },
        { value: 'Kebapçı', label: 'Kebapçı' },
        { value: 'Pideci', label: 'Pideci' },
        { value: 'Deniz Ürünleri Restoranı', label: 'Deniz Ürünleri Restoranı' },
        { value: 'Ev Yemekleri Restoranı', label: 'Ev Yemekleri Restoranı' },
        { value: 'Tatlıcı & Dondurmacı', label: 'Tatlıcı & Dondurmacı' },
        { value: 'Çorbacı', label: 'Çorbacı' },
        { value: 'Meyhane', label: 'Meyhane' },
        { value: 'Paket Servis', label: 'Paket Servis' },
    ],
    'Alışveriş': [
        { value: 'Süpermarket & Bakkal', label: 'Süpermarket & Bakkal' },
        { value: 'AVM', label: 'AVM' },
        { value: 'Giyim Mağazası', label: 'Giyim Mağazası' },
        { value: 'Ayakkabı Mağazası', label: 'Ayakkabı Mağazası' },
        { value: 'Elektronik Mağazası', label: 'Elektronik Mağazası' },
        { value: 'Mobilya Mağazası', label: 'Mobilya Mağazası' },
        { value: 'Kitapçı & Kırtasiye', label: 'Kitapçı & Kırtasiye' },
        { value: 'Kozmetik Mağazası', label: 'Kozmetik Mağazası' },
        { value: 'Oyuncakçı', label: 'Oyuncakçı' },
        { value: 'Çiçekçi', label: 'Çiçekçi' },
        { value: 'Kuyumcu', label: 'Kuyumcu' },
        { value: 'Pet Shop', label: 'Pet Shop' },
        { value: 'Manav & Kasap', label: 'Manav & Kasap' },
        { value: 'Hırdavatçı', label: 'Hırdavatçı' },
    ],
    'Sağlık & Medikal': [
        { value: 'Hastane', label: 'Hastane' },
        { value: 'Eczane', label: 'Eczane' },
        { value: 'Diş Kliniği', label: 'Diş Kliniği' },
        { value: 'Tıp Merkezi', label: 'Tıp Merkezi' },
        { value: 'Aile Sağlığı Merkezi', label: 'Aile Sağlığı Merkezi' },
        { value: 'Veteriner', label: 'Veteriner' },
        { value: 'Gözlükçü & Optik', label: 'Gözlükçü & Optik' },
        { value: 'Psikolog', label: 'Psikolog' },
        { value: 'Diyetisyen', label: 'Diyetisyen' },
        { value: 'Fizyoterapi Merkezi', label: 'Fizyoterapi Merkezi' },
        { value: 'Medikal Malzeme', label: 'Medikal Malzeme' },
    ],
    'Güzellik & Kişisel Bakım': [
        { value: 'Kuaför', label: 'Kuaför' },
        { value: 'Berber', label: 'Berber' },
        { value: 'Güzellik Salonu', label: 'Güzellik Salonu' },
        { value: 'SPA & Masaj Salonu', label: 'SPA & Masaj Salonu' },
        { value: 'Solaryum', label: 'Solaryum' },
        { value: 'Dövme & Piercing Stüdyosu', label: 'Dövme & Piercing Stüdyosu' },
    ],
    'Otomotiv': [
        { value: 'Oto Tamir & Bakım', label: 'Oto Tamir & Bakım' },
        { value: 'Oto Yıkama & Kuaför', label: 'Oto Yıkama & Kuaför' },
        { value: 'Lastikçi', label: 'Lastikçi' },
        { value: 'Benzin İstasyonu', label: 'Benzin İstasyonu' },
        { value: 'Oto Galeri', label: 'Oto Galeri' },
        { value: 'Otopark', label: 'Otopark' },
        { value: 'Oto Ekspertiz', label: 'Oto Ekspertiz' },
        { value: 'Yedek Parça', label: 'Yedek Parça' },
        { value: 'Rent a Car', label: 'Rent a Car' },
    ],
    'Eğlence & Etkinlik': [
        { value: 'Sinema', label: 'Sinema' },
        { value: 'Tiyatro', label: 'Tiyatro' },
        { value: 'Müze & Sanat Galerisi', label: 'Müze & Sanat Galerisi' },
        { value: 'Konser Alanı', label: 'Konser Alanı' },
        { value: 'Bowling Salonu', label: 'Bowling Salonu' },
        { value: 'Eğlence Parkı & Lunapark', label: 'Eğlence Parkı & Lunapark' },
        { value: 'Oyun Salonu', label: 'Oyun Salonu' },
        { value: 'Park & Mesire Alanı', label: 'Park & Mesire Alanı' },
        { value: 'Hayvanat Bahçesi', label: 'Hayvanat Bahçesi' },
    ],
    'Spor & Fitness': [
        { value: 'Spor Salonu & Fitness Merkezi', label: 'Spor Salonu & Fitness Merkezi' },
        { value: 'Halı Saha', label: 'Halı Saha' },
        { value: 'Yüzme Havuzu', label: 'Yüzme Havuzu' },
        { value: 'Tenis Kortu', label: 'Tenis Kortu' },
        { value: 'Basketbol Sahası', label: 'Basketbol Sahası' },
        { value: 'Yoga & Pilates Stüdyosu', label: 'Yoga & Pilates Stüdyosu' },
    ],
    'Profesyonel Hizmetler': [
        { value: 'Emlakçı', label: 'Emlakçı' },
        { value: 'Kargo & Nakliyat', label: 'Kargo & Nakliyat' },
        { value: 'Kuru Temizleme & Terzi', label: 'Kuru Temizleme & Terzi' },
        { value: 'Fotoğrafçı', label: 'Fotoğrafçı' },
        { value: 'Matbaa & Reklam Ajansı', label: 'Matbaa & Reklam Ajansı' },
        { value: 'Organizasyon Şirketi', label: 'Organizasyon Şirketi' },
        { value: 'Danışmanlık Hizmetleri', label: 'Danışmanlık Hizmetleri' },
        { value: 'İnternet Cafe', label: 'İnternet Cafe' },
    ],
    'Ev & Bahçe Hizmetleri': [
        { value: 'Tesisatçı', label: 'Tesisatçı' },
        { value: 'Elektrikçi', label: 'Elektrikçi' },
        { value: 'Çilingir', label: 'Çilingir' },
        { value: 'Temizlik Şirketi', label: 'Temizlik Şirketi' },
        { value: 'Peyzaj & Bahçıvanlık', label: 'Peyzaj & Bahçıvanlık' },
        { value: 'İlaçlama Servisi', label: 'İlaçlama Servisi' },
    ],
    'Eğitim': [
        { value: 'Okul (İlk/Orta/Lise)', label: 'Okul (İlk/Orta/Lise)' },
        { value: 'Üniversite', label: 'Üniversite' },
        { value: 'Sürücü Kursu', label: 'Sürücü Kursu' },
        { value: 'Dil Okulu', label: 'Dil Okulu' },
        { value: 'Kreş & Anaokulu', label: 'Kreş & Anaokulu' },
        { value: 'Dershane & Etüt Merkezi', label: 'Dershane & Etüt Merkezi' },
        { value: 'Müzik & Sanat Kursu', label: 'Müzik & Sanat Kursu' },
    ],
    'Finans & Hukuk': [
        { value: 'Banka', label: 'Banka' },
        { value: 'ATM', label: 'ATM' },
        { value: 'Avukatlık & Hukuk Bürosu', label: 'Avukatlık & Hukuk Bürosu' },
        { value: 'Noter', label: 'Noter' },
        { value: 'Muhasebeci & Mali Müşavir', label: 'Muhasebeci & Mali Müşavir' },
        { value: 'Sigorta Acentesi', label: 'Sigorta Acentesi' },
    ],
    'Konaklama & Seyahat': [
        { value: 'Otel', label: 'Otel' },
        { value: 'Pansiyon', label: 'Pansiyon' },
        { value: 'Apart Otel', label: 'Apart Otel' },
        { value: 'Misafirhane', label: 'Misafirhane' },
        { value: 'Kamp Alanı', label: 'Kamp Alanı' },
        { value: 'Turizm Acentesi', label: 'Turizm Acentesi' },
    ],
    'Kamu & Dini Kuruluşlar': [
        { value: 'Belediye & Kaymakamlık', label: 'Belediye & Kaymakamlık' },
        { value: 'Muhtarlık', label: 'Muhtarlık' },
        { value: 'Postane (PTT)', label: 'Postane (PTT)' },
        { value: 'Adliye', label: 'Adliye' },
        { value: 'Cami', label: 'Cami' },
        { value: 'Kilise', label: 'Kilise' },
        { value: 'Dernek & Vakıf', label: 'Dernek & Vakıf' },
    ]
};